### ISSUE TITLE
Can't find memdown on Ubuntu install

### ISSUE THREAD

**Issue by cobbr2** [mhart/kinesalite#35]
This is almost certainly user error or a config problem on my machine, but having little experience with node, figured I'd ask here.

I installed using the instructions:
```
rcobb@rcobb-x250: /usr/local/bin$ sudo npm install -g kinesalite
npm ERR! not a package /home/rcobb/tmp/npm-21039-pyzsYb2e/1467417729931-0.7627380455378443/tmp.tgz
npm http GET https://registry.npmjs.org/kinesalite
npm http 304 https://registry.npmjs.org/kinesalite
npm http GET https://registry.npmjs.org/async
...
npm http 304 https://registry.npmjs.org/es6-iterator

> leveldown@1.4.6 install /usr/local/lib/node_modules/kinesalite/node_modules/leveldown
> prebuild --install

/usr/local/bin/kinesalite -> /usr/local/lib/node_modules/kinesalite/cli.js
kinesalite@1.11.5 /usr/local/lib/node_modules/kinesalite
├── lock@0.1.2
├── node-uuid@1.4.7
├── minimist@1.2.0
├── lazy@1.0.11
├── async@1.5.2
├── once@1.3.3 (wrappy@1.0.2)
├── bignumber.js@2.3.0
├── memdown@1.2.0 (inherits@2.0.1, ltgt@1.0.2, functional-red-black-tree@1.0.1, abstract-leveldown@2.6.0)
├── levelup@1.3.2 (xtend@4.0.1, prr@1.0.1, level-codec@6.1.0, semver@5.1.1, level-errors@1.0.4, deferred-leveldown@1.2.1, level-iterator-stream@1.3.1)
├── level-sublevel@6.5.4 (typewiselite@1.0.0, ltgt@2.1.2, xtend@4.0.1, pull-stream@2.21.0, bytewise@1.1.0, levelup@0.19.1)
└── leveldown@1.4.6 (bindings@1.2.1, fast-future@1.0.1, abstract-leveldown@2.4.1, nan@2.3.5, prebuild@4.2.2)
```

But when I run I get:

```
rcobb@rcobb-x250: /usr/local/bin$ kinesalite

module.js:340
    throw err;
          ^
Error: Cannot find module 'memdown'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/kinesalite/db/index.js:4:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

I'm using ubuntu and:
```
rcobb@rcobb-x250: /usr/local/bin$ uname -a
Linux rcobb-x250 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
rcobb@rcobb-x250: /usr/local/bin$ node -v
v0.10.25
rcobb@rcobb-x250: /usr/local/bin$ npm -v
1.3.10
```

Any tips? 

Thanks.

**Comment by mhart** [comment]
@cobbr2 pretty sure that's just down to the fact that you're using a *really* old version of npm. Latest is v3.x but even v2.x should be fine. Try `npm install -g npm@latest` before installing kinesalite – and you might need to completely clear the npm cache, etc too: `npm cache clean`

**Comment by mhart** [comment]
In fact, I'm like 99% sure you're running into the same issue as this: https://github.com/mhart/dynalite/issues/51

**Comment by cobbr2** [comment]
Thanks, @mhart .  I had the same problem with the LTS (4.4) version of `node` & `npm`, but after installing the "current" versions of node & npm, kinesalite starts up just fine.  Onward.

```
rcobb@rcobb-x250: (feature/120392275/use-kinesis-emulator-in-pancakes) ~/service$ node --version
v6.2.2
rcobb@rcobb-x250: (feature/120392275/use-kinesis-emulator-in-pancakes) ~/service$ npm --version
3.9.5
rcobb@rcobb-x250: (feature/120392275/use-kinesis-emulator-in-pancakes) ~/service$ kinesalite 
Listening at http://:::4567
```

**Comment by mhart** [comment]
kinesalite [definitely works on Node.js v4](https://travis-ci.org/mhart/kinesalite/jobs/141420155) (it even [works on v0.10](https://travis-ci.org/mhart/kinesalite/jobs/141420153)), but it may be that you were running into some npm cache issues that cleared up with the upgrade to npm v3.x

Glad you got it working! 👍
