### ISSUE TITLE
Cannot create stream: Forbidden 403 http error

### ISSUE THREAD

**Issue by ptaillard** [mhart/kinesalite#53]
Hello,

I use kinesalite and I want to create a Java producer which write in the Kinesalite stream.

To do that, I start kinesalite using default port and wrote this code:
```
BasicAWSCredentials awsCreds = new BasicAWSCredentials("FAKE", "FAKE");
kinesisClient = new AmazonKinesisAsyncClient(awsCreds);
kinesisClient.setRegion(Region.getRegion(Regions.US_EAST_1));
kinesisClient.setEndpoint("http://localhost:4567");
kinesisClient.createStream("mystream", 1);
```

But application throw an exception:
```
Caused by: com.amazonaws.services.kinesis.model.AmazonKinesisException: null (Service: AmazonKinesis; Status Code: 403; Error Code: null; Request ID: 8f0a2180-add3-11e7-8534-49848585881a)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1638)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1303)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1055)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.doInvoke(AmazonKinesisClient.java:2219)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.invoke(AmazonKinesisClient.java:2195)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.executeCreateStream(AmazonKinesisClient.java:458)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.createStream(AmazonKinesisClient.java:434)
	at com.amazonaws.services.kinesis.AmazonKinesisClient.createStream(AmazonKinesisClient.java:470)
```

When I look closer, I notice that the response is about credentials:
```
HTTP/1.1 403 Forbidden [x-amzn-RequestId: db224e20-add4-11e7-8534-49848585881a, x-amz-id-2: IEeIw2SzHkV5cnKy2q8rBGdm2Ik0NyEvLAqIk4ex5XVuzI7W3nNw/Mmpr1AdLZ5uIx6r4AOQK/pXq8pe2rhBvUOn0skAScJX, Content-Length: 130, Date: Tue, 10 Oct 2017 16:05:37 GMT, Connection: keep-alive] ResponseEntityProxy{[Content-Length: 130,Chunked: false]}
```

And request I made on kinesalite is:
```
POST http://localhost:4567/ HTTP/1.1
Headers [Host: localhost:4567, Authorization: AWS4-HMAC-SHA256 Credential=FAKE/20171010/us-east-1/kinesis/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-date;x-amz-target, Signature=cbbd5f388018a2d8c36adabf72914398a551b2c9f5bb12ff7a59ab224df45ed6, X-Amz-Date: 20171010T155620Z, User-Agent: aws-sdk-java/1.11.198 Mac_OS_X/10.12.1 Java_HotSpot(TM)_64-Bit_Server_VM/25.111-b14 java/1.8.0_111 scala/2.10.0, amz-sdk-invocation-id: 7da5b848-f2be-b9c6-16a3-5ebd04a7d02b, amz-sdk-retry: 0/0/500, X-Amz-Target: Kinesis_20131202.CreateStream, Content-Type: application/x-amz-cbor-1.1]
```

Have you an idea of how to fix that? I need to set credentials when I try to connect to kinesalite?

Many thanks

**Comment by mhart** [comment]
You're trying to connect using CBOR (which is the Java default). kinesalite does not support CBOR, only JSON: https://github.com/mhart/kinesalite#cbor-protocol-issues-with-the-java-sdk

**Comment by ptaillard** [comment]
Thanks @mhart
